language: node_js
repo_token: Mb9CVhxHbtiBWsN5CY2Dop4qqKLUf46Oh
node_js:
- 5
before_script:
- npm run test
- npm run coverage
script: npm run build
after_success: "< coverage/lcov-report/*html ./node_modules/coveralls/bin/coveralls.js"